### ISSUE TITLE
How do you install these in Sublime 3?

### ISSUE THREAD

**Issue by mindjuice** [uloco/webstorm-bluloco-scheme#3]
I can't seem to find any info online about installing IntelliJ themes or `.icls` files in Sublime Text 3.

I've tried putting the `.jar` and the `.icls` files in various places under the `Packages` folder, but haven't hit the right spot yet.

What file(s) should go where?

p.s. I love BluLoco Light!

**Comment by uloco** [comment]
Thanks for that. I moved the sublime support out of this repository because it was outdated. You can use the following git repo for the tmTheme version. I build it from scratch for visual studio code, but it should also work in sublime, because they both use the tmTheme format. (It is in the folder *themes*)
https://github.com/uloco/theme-bluloco-dark
https://github.com/uloco/theme-bluloco-light

**Comment by mindjuice** [comment]
Thanks.  Got it working in Sublime 3.

Just for those who don't know, this page tells you how to install a TextMate color theme in Sublime 3 (reproduced below for easy access):  https://packagecontrol.io/packages/Theme%20-%20Soda

I've adapted those instructions to `bluloco-light` below:

- Download the file using the GitHub .zip download option
- Find your Sublime Text Packages directory using the Sublime menu item `Preferences -> Browse Packages...`
- Unzip the files and copy the `bluloco-light.tmTheme` file to a folder called `Bluloco-Light` in your Sublime Text Packages directory

**Comment by uloco** [comment]
Why should anyone look for a soda theme installation in my bluloco repository?

**Comment by mindjuice** [comment]
Derp...didn't notice that the bit I copied and pasted mentioned Soda.  Updated comment above.
